### ISSUE TITLE
《问题》校验时边框样式不对，

### ISSUE THREAD

**Issue by Wang-yubo** [yigexiaoairen/am-editable#6]
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/59524432/187859950-34dbc0bf-3770-43e6-819f-cd51376fdc5e.png">
input框在校验失败时 少了 “ant-input-status-error” 这是为啥呢

**Comment by Wang-yubo** [comment]
好像是antd的问题，4.19以上都不行了，4.19以下也只有部分版本才是正常的。不知道是不是为了配合Form.Item.useStatus();给改了。

**Comment by Wang-yubo** [comment]
@yigexiaoairen 请问下这个问题可以解决吗？

**Comment by yigexiaoairen** [comment]
看了一下是因为antd更新了组件结构以及样式，导致错误提示没有显示红色；可以设置一下面这个样式解决这个问题；后面我会针对antd结构变更更新一个版本

```less
.ant-form-item-has-error .ant-form-item-explain-error {
  color: #ff4d4f;
}

.ant-form-item-has-error .ant-input:focus {
  border-color: #ff7875;
  border-right-width: 1px!important;
  outline: 0;
  box-shadow: 0 0 0 2px rgb(255 77 79 / 20%);
}
```
